name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: Test the action
    steps:
      - uses: actions/checkout@v2
        
      - name: Get code coverage
        uses: ./ # Uses an action in the root directory
        id: test_step
        with:
          label: "Code Coverage"
          color: "blue"
          path: "test/coverage.opencover.xml"
          gist-filename: "code-coverage.json"
          gist-id: "7b6fcd8cecf36e9cc83276540e9f2867"
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}

      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.test_step.outputs.percentage}}%"

      - name: Print badge data
        run: echo "Badge data ${{steps.test_step.outputs.badge}}"