name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: Test the action
    steps:
      - uses: actions/checkout@v2
        
      - name: Get code coverage
        uses: ./ # Uses an action in the root directory
        id: test_step
        with:
          label: "My Label"
          color: "red"
          path: "test/coverage.opencover.xml"
        
      - name: Print code coverage
        run: echo "Code coverage percentage ${{steps.test_step.outputs.percentage}}%"

      - name: Print badge data
        run: echo "Badge data ${{steps.test_step.outputs.badge}}"